name: mi_card
description: A new Flutter application.

version: 1.0.0+1

flutter_icons:
  image_path: "images/mi.png"
  android: true
  ios: true

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  url_launcher: 6.1.2

  flutter_launcher_icons: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/hamter.png
    - images/hamter.gif
    - images/7RRt.gif

  fonts:
    - family: ArchitectsDaughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: ZenDots
      fonts:
            - asset: fonts/ZenDots-Regular.ttf



